### ISSUE TITLE
Trigger every second week

### ISSUE THREAD

**Issue by mastertinner** [concourse/time-resource#13]
In our team we have sprints that last for two weeks and would like to deploy at the end of every sprint. Is it somehow possible to trigger the resource on every second Friday only? Can the `interval` be set to `14days`? Or can we introduce an optional parameter to trigger only on odd/even numbered weeks? I'm not sure what's the best way here but I think this might be useful to some other teams as well.

**Comment by jtarchie** [comment]
@mastertinner, the duration can be specified in `14d` increments. We are refraining from have the resource emulate `cron` as it is a different paradigm. Try the [cron resource](https://github.com/pivotal-cf-experimental/cron-resource) to see if that fits you better.
