### ISSUE TITLE
Manual triggers prevented when a nightly trigger has no version

### ISSUE THREAD

**Issue by devdavidkarlsson** [concourse/time-resource#14]
The pipeline gets stuck like this:

x checking pipeline is not paused
x checking job is not paused
x discovering any new versions of devops-repo
x discovering any new versions of ios-repo
x discovering any new versions of mock-server-repo
o discovering any new versions of nightly
o waiting for a suitable set of input versions
    o nightly - no versions available
x checking max-in-flight is not reached

This is a blocker for using this trigger, I need to be able to trigger manually as well...

**Comment by dcarastan** [comment]
+1 on this feature. Passing trigger context info to the time resource environment would allow it to report as being ready and report the check event time instead of blocking.

**Comment by andrewedstrom** [comment]
@devdavidkarlsson @dcarastan Would this issue be solved if we added a zero time, as in concourse/time-resource#11?

**Comment by jtarchie** [comment]
@andrewedstrom, is correct, this would be corrected with concourse/time-resource#11.
