### ISSUE TITLE
Interval is a required field, documentation should be corrected

### ISSUE THREAD

**Issue by jklemens** [concourse/time-resource#18]
In the time resource documentation, there is an example called "Trigger once within time range" that should allow for a time trigger to fire exactly once within a time range.  However, this example does not work as written.  The trigger does not fire without the interval field being explicitly defined.

For example, for a once a day trigger an interval of "24h" needs to be set for the time resource to trigger a downstream job properly.

**Comment by jtarchie** [comment]
@jklemens, do you have an example where it does not work for you? I've followed that pattern many times (not specifying an `interval`) and it worked fine.
