### ISSUE TITLE
Can't manually trigger a pipeline outside time range

### ISSUE THREAD

**Issue by jordimassaguerpla** [concourse/time-resource#24]
Hi,
I would like to be able to trigger a pipeline manually even if it is out of the time range define with this resource.

However, If I tried, it gets stuck on "checking for new version"

However, I can run it manually if I use the time interval as "24h". But that does not  let me specify a specific time.

Could you please make the "time range" be also triggered manually?

**Comment by neongreen** [comment]
Apparently it works once the resource has been created -- i.e. here are the steps:

* Set `time` to 24h (or whatever that includes the current time)
* Stop the pipeline
* Set `time` back to what you want it to be
* From now on you should be able to trigger the pipeline manually.

**Comment by goldstar611** [comment]
I just ran into this bug too for a new pipeline. It's not possible to manually trigger the build until the "time window" passes OR you adjust the time-resource manually to let it create the resource as neongreen mentioned above.

**Comment by owenfarrell** [comment]
You should be able to use a variation of the solution provided in https://github.com/concourse/time-resource/issues/11#issuecomment-562385742.

```
fly -t <your target> check-resource <your resource>
   --from "time:2020-07-13T06:00:00-0400" # make sure this timestamp is in the *most recent* time range
```

**Comment by kallisti5** [comment]
This workaround no longer works in 6.x anyone have a new solution?

```
fly -t <target> check-resource -r <resource> --from "time:2020-07-13T06:00:00-0400"
```

```
parse error: parsing time ""2020-07-13T06:00:00-0400"" as ""2006-01-02T15:04:05Z07:00"": cannot parse "-0400"" as "Z07:00"
```

**Comment by boekkooi-fresh** [comment]
@kallisti5 try using `fly -t <target>  check-resource -r <resource> --from "time:2020-09-09T05:00:05Z"` It looks like the time format was changed.
